import "./globals.css";
import { Inter } from "next/font/google";
import { UserProvider } from "./UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Survey Valley",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </UserProvider>
  );
}
